### ISSUE TITLE
UI issue with Sticky Header on Configuration change

### ISSUE THREAD

**Issue by MuhammadRashid** [sokarcreative/BasicStuffRecyclerview#1] opened 2018-01-10 20:29 UTC
Hi Dev Team, 
I am getting a UI issue with Sticky Header on Configuration change. The first visible Sticky Header does not draw/show text properly and cut sticky view's length to half. Once I scroll recycler view, it works fine.

**Comment by sokarcreative** [comment] 2018-01-11 07:21
I didn't test when configuration changed. I will see that tonight, thx for reporting :)

**Comment by sokarcreative** [comment] 2018-01-11 08:36
With a quick test, it seems to work well for me using the demo app. 
Are you using android:layout_width="match_parent" in your root viewHolder layout ?
When such a change occurs, the view is recreated so it should work.

**Comment by MuhammadRashid** [comment] 2018-01-14 16:19
Please note that I am using android:configChanges="orientation|keyboardHidden|screenSize" for activity. PFA  screenshots with Portrait and Landscape modes.

**Portrait Mode:**
<img width="310" alt="portrait_mode" src="https://user-images.githubusercontent.com/10269811/34918160-2814e26a-f970-11e7-8f8c-c813986737dd.png">

**Landscape Mode:**
1.
<img width="480" alt="landscape_mode_1" src="https://user-images.githubusercontent.com/10269811/34918164-33b55ad2-f970-11e7-92ed-ade56a89f6de.png">

2.
<img width="479" alt="landscape_mode_2" src="https://user-images.githubusercontent.com/10269811/34918165-381d6146-f970-11e7-80d4-f216674b9e23.png">

**Comment by MuhammadRashid** [comment] 2018-01-14 16:22
Yes I am using android:layout_width = "match_parent"

**Comment by sokarcreative** [comment] 2018-01-16 08:03
I think I know what it is, I will see that tonight

**Comment by sokarcreative** [comment] 2018-01-18 09:42
I tried to reproduce the same behaviour but no way.
Can you tell me which android version you use ?

**Comment by MuhammadRashid** [comment] 2018-01-20 10:15
I tested on android versions "6.0.1" and "8.0.0". Please also note that in order to handle config changes I used "android:configChanges="orientation|keyboardHidden|screenSize"

**Comment by sokarcreative** [comment] 2018-01-20 11:30
Yeah I tried too but it works, there is no reason it doesn't draw correctly, It's kinda strange.. I can't solve it unless you give me an example project with this issue which I can see where is the problem. I'm using this library in many projects (that's why I created this one obsviously) and I have never seen this behaviour before. Sry if I can't help you right now.

**Comment by sokarcreative** [comment] 2018-01-20 11:37
Ok I see the problem

**Comment by sokarcreative** [comment] 2018-01-20 11:45
I cached the current sticky header until there is another one for better performance but since screenSize didn't recreate the view, it keeps the same stickyView instance until there is another one. What I need to do is invalidate the current sticky header on configuration changed when ScreenSize is used. Thx for reporting.

**Comment by MuhammadRashid** [comment] 2018-01-20 13:40
Kindly update the Code so I can get latest from git.

**Comment by sokarcreative** [comment] 2018-01-20 16:13
Problem solved 👍 
implementation 'com.github.sokarcreative:BasicStuffRecyclerview:0.2.1'

I removed the cache system. I tried first to find a workaround with SensorEvent to invalidate the cache and it worked 3/4 times but onDrawOver was called sometimes before the sensorEvent, so it didn't always work. performance shouldn't be a lot affected anyway.

**Comment by MuhammadRashid** [comment] 2018-01-23 05:21
Yes it works like a charm. Thank you very much. 

Please also note that there is another issue. You can see in above Portrait Mode Screenshot, the background difference b/w sticky header's background and other header's background. Both are not same.

**Comment by sokarcreative** [comment] 2018-01-23 07:32
If it's solved, I'm closing this issue. Could you open another one ? If you are talking about the bottom divider missing in sticky header, you should take a look in the demo app, there is an example.

**Closed as completed by sokarcreative** 2018-01-23 07:32 UTC
